const SahteVeri=[
    {
        id:1,
        name:"Tunahan",
        surname:"Ates",
        email:"tuna@gmail.com",
        age:"23"
    },
    {
        id:2,
        name:"Buse",
        surname:"Partal",
        email:"buse@gmail.com",
        age:"21"
    },
    {
        id:1,
        name:"Tunahan",
        surname:"Ates",
        email:"tuna@gmail.com",
        age:"23"
    },
    {
        id:2,
        name:"Buse",
        surname:"Partal",
        email:"buse@gmail.com",
        age:"21"
    },
    {
        id:1,
        name:"Tunahan",
        surname:"Ates",
        email:"tuna@gmail.com",
        age:"23"
    },
    {
        id:2,
        name:"Buse",
        surname:"Partal",
        email:"buse@gmail.com",
        age:"21"
    }
]
export default SahteVeri;